--db links-------------------------------------------------
--select * from dba_db_links x where x.owner='PUBLIC';
--drop user xyz cascade;
--drop public database link live
select * from dba_source x where upper(x.TEXT) like '%ENBREP%';

DECLARE
  L_SEARCH VARCHAR2(1000) := upper('modern_users');
  L_CHAR VARCHAR2(32767);
BEGIN
  FOR REC IN (SELECT * FROM ALL_VIEWS WHERE TEXT_LENGTH < 32767 ORDER BY OWNER,VIEW_NAME)
  LOOP
    L_CHAR := UPPER(REC.TEXT);
    IF (INSTR(L_CHAR, L_SEARCH) > 0) THEN
      DBMS_OUTPUT.PUT_LINE('' || REC.OWNER || '.' || REC.VIEW_NAME);
    END IF;
  END LOOP;
END;


--users-------------------------------------------------

 
 
 
SELECT A.USERNAME,
       A.ACCOUNT_STATUS,
       TO_CHAR(B.PTIME, 'YYYY/MM/DD HH24:MI:SS', 'NLS_CALENDAR=PERSIAN') AS PASSWORD_DATE,
       TO_CHAR(A.LOCK_DATE, 'YYYY/MM/DD HH24:MI:SS', 'NLS_CALENDAR=PERSIAN') AS LOCK_DATE,
       TO_CHAR(A.EXPIRY_DATE,'YYYY/MM/DD HH24:MI:SS','NLS_CALENDAR=PERSIAN') AS EXPIRY_DATE,
       TO_CHAR(A.CREATED, 'YYYY/MM/DD HH24:MI:SS', 'NLS_CALENDAR=PERSIAN') AS CREATED,
       A.PROFILE,
       A.DEFAULT_TABLESPACE,
       A.TEMPORARY_TABLESPACE
  FROM DBA_USERS A, USER$ B
 WHERE 
   1 = 1
   AND A.USERNAME = B.NAME
   AND A.USERNAME NOT IN ('XDB','TSMSYS','TRACESVR','SYSTEM','SYS','SCOTT','ADAMS','JONES','CLARK','BLAKE','PERFSTAT','OUTLN','ORDSYS','ORDPLUGINS','ORACLE_OCM','MDSYS','LBACSYS','HR(HUMANRESOURCES)','OE(ORDERENTRY)','SH(SALESHISTORY)','EXFSYS','DSSYS','DMSYS','DIP','DEMO','DBSNMP','CTXSYS','CSMIG','AWR_STAGE','AURORA$ORB$UNAUTHENTICATED','ANONYMOUS','APPQOSSYS','WMSYS','ORDDATA','SI_INFORMTN_SCHEMA','OLAPSYS','MDDATA','SPATIAL_WFS_ADMIN_USR','SPATIAL_CSW_ADMIN_USR','SYSMAN','MGMT_VIEW','FLOWS_FILES','APEX_PUBLIC_USER','APEX_030200','OWBSYS','OWBSYS_AUDIT','DEV_ODI_REPO','GOLDENGATE','GOLDENGATE_LOGIN','OWB_OWNER','XS$NULL','ODS')
 ORDER BY A.USERNAME;
 
--DB LINK CHANGE--------------------------------------------------------------------------



ALTER USER GUARD_BAHRAMI IDENTIFIED BY 123 ACCOUNT UNLOCK;
GRANT CREATE DATABASE LINK TO GUARD_BAHRAMI;
GRANT CREATE SESSION TO GUARD_BAHRAMI;
CONNECT GUARD_BAHRAMI/123
DROP DATABASE LINK GUARD_BAHRAMI_PRIVATE;
CREATE DATABASE LINK GUARD_BAHRAMI_PRIVATE CONNECT TO REPORT_VIEW IDENTIFIED BY xxxx USING 'GUARD_BAHRAMI';
CONNECT / AS SYSDBA
ALTER USER GUARD_BAHRAMI IDENTIFIED BY XYQASDASDASD213SS ACCOUNT LOCK;
REVOKE CREATE DATABASE LINK FROM GUARD_BAHRAMI;
REVOKE CREATE SESSION FROM GUARD_BAHRAMI;

