SET COLSEP ,
SET HEADSEP OFF
SET PAGESIZE 0
SET TRIMSPOOL ON
SET ECHO OFF
SET FEEDBACK OFF
SPOOL get_oracle_tablespaces.csv
SELECT TABLESPACE || ',' || TOTAL_SPACE_MB || ',' || USED_SPACE_MB || ',' || DATA_FILES_COUNT AS RES
FROM
(
SELECT A.TABLESPACE,
       SUM(A.TOTAL) AS TOTAL_SPACE_MB,
       SUM(A.USED) AS USED_SPACE_MB,
       COUNT(*) AS DATA_FILES_COUNT
  FROM SYS.ENBDBA_TABLESPACES A
 GROUP BY A.TABLESPACE
);
SPOOL OFF;
EXIT;




