PURGE DBA_RECYCLEBIN;
SELECT * FROM ENBDBA_TABLESPACES;
SELECT X.OWNER,SUM(X.BYTES)/1024/1024/1024 AS GB FROM DBA_SEGMENTS X 
GROUP BY X.OWNER
ORDER BY 2 DESC;
SELECT * FROM DBA_SEGMENTS X WHERE X.OWNER='...';

SELECT 'ALTER TABLE ' || OWNER || '.' || OBJECT_NAME || ' MOVE TABLESPACE '||' NEW_TBS; '
FROM ALL_OBJECTS
WHERE OWNER = '...'
AND OBJECT_TYPE = 'TABLE'


SELECT 'ALTER TABLE ' || W.OWNER || '.' || W.SEGMENT_NAME || ' MOVE TABLESPACE TBS_' || W.OWNER || ' PARALLEL;' FROM DBA_SEGMENTS W WHERE W.OWNER='...' AND SEGMENT_TYPE='TABLE' AND TABLESPACE_NAME='...'
UNION ALL
SELECT 'ALTER INDEX ' || W.OWNER || '.' || W.INDEX_NAME || ' REBUILD TABLESPACE TBS_' || W.OWNER || ' NOLOGGING PARALLEL;' FROM DBA_INDEXES W WHERE W.OWNER='...' AND W.TABLESPACE_NAME='...';



SELECT 
'ALTER TABLE ' || A.OWNER || '.' || A.TABLE_NAME || ' MOVE LOB(' || A.COLUMN_NAME || ') STORE AS ( TABLESPACE NEW_TABLESPACE_NAME );' AS COMMAND
 FROM DBA_LOBS A
WHERE A.OWNER='...' AND A.TABLESPACE_NAME='...'






ALTER TABLE ... MOVE PARTITION ... TABLESPACE ... NOLOGGING COMPRESS;