ARCHIVE LOG LIST
SHOW PARAMETER RECOVERY_FILE_DEST
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=/u02/app/oracle/oradata/orcl/arch' SCOPE = BOTH;
SHUTDOWN IMMEDIATE;
STARTUP MOUNT
ALTER DATABASE ARCHIVELOG;
--ALTER DATABASE NOARCHIVELOG;
ALTER DATABASE OPEN;

ALTER SYSTEM SWITCH LOGFILE;
