CREATE USER USER_NAME IDENTIFIED BY PASSWORD 
ACCOUNT LOCK
DEFAULT TABLESPACE TBS_NAME
QUOTA UNLIMITED ON TBS_NAME
PROFILE PROFILE_NAME;

ALTER USER USER_NAME IDENTIFIED BY PASSWORD 
ACCOUNT LOCK
DEFAULT TABLESPACE TBS_NAME
QUOTA UNLIMITED ON TBS_NAME
PROFILE PROFILE_NAME;

SELECT * FROM DBA_USERS;
SELECT * FROM USER$;

DROP USER USER_NAME CASCADE;


