BEGIN
	DBMS_SQLTUNE.CREATE_SQLSET
	(
		SQLSET_NAME => 'GIFTCARD_SQLSET1',
		DESCRIPTION => 'THIS SQLSET IS CREATED FOR MR MAZLOOMI 20171003'
	);
END;




 SELECT DBMS_SQLTUNE.REPORT_SQL_MONITOR(SQL_ID => '16DH92BJGPKVS',TYPE => 'TEXT' , REPORT_LEVEL => 'ALL') AS REPORT FROM DUAL;