SELECT B.USERNAME,
       A.SQL_TEXT,
       A.SQL_FULLTEXT,
       A.SQL_ID,
       A.ELAPSED_TIME / 1000 / 1000 AS ELAPSED_TIME_SECONDS,
       A.CHILD_NUMBER,
       A.DISK_READS,
       A.EXECUTIONS,
       A.FIRST_LOAD_TIME,
       A.LAST_LOAD_TIME
  FROM V$SQL A, V$SESSION B
 WHERE A.SQL_ID = B.SQL_ID
 ORDER BY ELAPSED_TIME DESC
