CREATE OR REPLACE PACKAGE CRM_FILTERS_PACK AS
FUNCTION FILTER_FUNC01(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC02(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC03(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC04(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC05(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC06(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC07(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC08(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC09(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC10(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC11(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC12(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC13(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC14(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC15(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC16(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC17(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC18(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC19(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC20(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC21(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC22(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC23(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC24(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC25(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC26(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC27(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC28(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC29(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC30(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC31(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC32(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC33(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
FUNCTION FILTER_FUNC34(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) RETURN VARCHAR2;
END CRM_FILTERS_PACK;


CREATE OR REPLACE PACKAGE BODY CRM_FILTERS_PACK AS


FUNCTION FILTER_FUNC01(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'BAIL_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC01;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC02(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CF_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC02;
---------------------------------------------------------------------------------------- 
FUNCTION FILTER_FUNC03(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'COLLAT_DEPOSIT_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC03;
---------------------------------------------------------------------------------------- 
FUNCTION FILTER_FUNC04(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)  
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC04;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC05(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)  
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CUSTOMER_NO_RELATED NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC05;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC06(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)  
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'DEPOSIT1_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC06;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC07(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)  
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'DEPOSIT2_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC07;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC08(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)  
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'DEPOSIT_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC08;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC09(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)  
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'DEST_DEPOSIT_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC09;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC10(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)  
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'LC_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC10;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC11(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)  
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'LOAN_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC11;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC12(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)  
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'SURETY_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC12;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC13(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CF_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR BAIL_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC13;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC14(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CF_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR LOAN_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC14;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC15(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR CUSTOMER_NO_RELATED NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC15;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC16(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR DEPOSIT_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC16;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC17(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'DEPOSIT2_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR DEPOSIT1_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC17;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC18(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR DEPOSIT_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC18;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC19(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR DEPOSIT_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC19;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC20(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'COLLAT_DEPOSIT_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR LOAN_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC20;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC21(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'COLLAT_DEPOSIT_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR LOAN_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC21;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC22(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'LOAN_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC22;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC23(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'LOAN_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR DEPOSIT_CUSTOMER_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC23;
----------------------------------------------------------------------------------------
------ZANJIREH
FUNCTION FILTER_FUNC24(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CC_CFCIFNO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR FILECIF NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC24;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC25(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CFCIFNO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC25;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC26(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CIF_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC26;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC27(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CUSTOMER_NUM NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR DPST_CUSTOMER_NUM NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC27;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC28(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'CUSTOMER_NUM1 NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER) OR CUSTOMER_NUM2 NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC28;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC29(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'MOTEAHED_CIF_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC29;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC30(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'ZI_CIF NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC30;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC31(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'ZI_CIF_NO NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC31;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC32(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2) 
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'ZINAFE_DEP_CIF NOT IN (SELECT CUSTOMER_NO FROM ENBDBA.CRM_CUSTOMERS_FILTER)';
END FILTER_FUNC32;
----------------------------------------------------------------------------------------
FUNCTION FILTER_FUNC33(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN 'SOURCE_CARD_KEY NOT IN (SELECT CARD_KEY FROM CUSTOMER_PROFILE_DEV.CUSTS_CARDS) OR DESTINATION_CARD_KEY NOT IN (SELECT CARD_KEY FROM CUSTOMER_PROFILE_DEV.CUSTS_CARDS)';
END FILTER_FUNC33;
END CRM_FILTERS_PACK;

FUNCTION FILTER_FUNC34(OBJECT_SCHEMA IN VARCHAR2,OBJECT_NAME VARCHAR2)
  RETURN VARCHAR2
 IS
 BEGIN
   RETURN '(DEPOSIT_BRANCH_CODE,DEPOSIT_TYPE,CUSTOMER_NO,DEPOSIT_SERIAL) NOT IN (SELECT * FROM ENBDBA.CRM_CUSTOMERS_FILTER_DEPOSITS)';
END FILTER_FUNC34;


/*BEGIN
DBMS_RLS.DROP_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S',
                      OBJECT_NAME     => 'CUSTS_CARDS_DEPOSITS',
                      POLICY_NAME     => 'CRM_DEPOSITS_FILTER');
END;*/
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_CREDIT_FILES_BAILS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 13',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC13',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_CREDIT_FILES_BATCHES',POLICY_NAME=>'CRM_DEPOSITS_FILTER 14',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC14',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_CUST2CUST',POLICY_NAME=>'CRM_DEPOSITS_FILTER 15',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC15',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_CUST2DEP',POLICY_NAME=>'CRM_DEPOSITS_FILTER 16',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC16',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_DEP2DEP',POLICY_NAME=>'CRM_DEPOSITS_FILTER 17',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC17',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_DEPOSITS_CARDS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 18',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC18',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_DEPOSITS_CARDS_NEW',POLICY_NAME=>'CRM_DEPOSITS_FILTER 19',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC19',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_LOANS_COLLATS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 20',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC20',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_LOANS_COLLATS_REPORT',POLICY_NAME=>'CRM_DEPOSITS_FILTER 21',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC21',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_LOANS_CUSTOMERS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 22',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC22',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CUSTOMER_PROFILE_S',OBJECT_NAME=>'CUSTS_LOANS_DEPOSIT',POLICY_NAME=>'CRM_DEPOSITS_FILTER 23',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC23',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_ADDRESS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CARDS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CARDS_DEPOSITS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CHEQUEBOOKS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CHEQUEBOOKS_DAILY' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CHEQUESHEETS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CHEQUES_TRANS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CREDIT_FILES' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 02',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC02 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CREDIT_FILES_02' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 02',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC02 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CREDIT_FILES_ACCOUNTS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 02',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC02 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CREDIT_FILES_BAILS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 02',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC02 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CREDIT_FILES_BAILS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 01',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC01 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CREDIT_FILES_BATCHES' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 02',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC02 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CREDIT_FILES_BATCHES' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CUST2CUST' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CUST2CUST' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 05',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC05 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CUST2DEP' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CUST2DEP' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_DEP2DEP' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 06',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC06 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_DEP2DEP' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 07',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC07 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_DEPOSITS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 34',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC34 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_DEPOSITS_CARDS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_DEPOSITS_CARDS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_DEPOSITS_CARDS_NEW' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_DEPOSITS_CARDS_NEW' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_DEPOSITS_DAILY' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_DEPOSITS_INT_RATE_DEP' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_INPUT_CHEQUES' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 09',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC09 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_JOB' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LC1' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 10',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC10 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LC2' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 10',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC10 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LC_STEPS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 10',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC10 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LEGAL' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_BANK_PAYMENTS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_COLLATS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_COLLATS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 03',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC03 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_COLLATS_HISTORY' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_COLLATS_REPORT' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_COLLATS_REPORT' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 03',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC03 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_CUSTOMERS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_CUSTOMERS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_DAILY' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_DEPOSIT' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_DEPOSIT' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_DURATION' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_IBAN' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_INSTALLMENT1' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_INSTALLMENT2' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_INSURANCE_PAYS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 11',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC11 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_SURETY' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 12',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC12 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_LOANS_SURETY_02' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 12',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC12 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_REAL' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 04',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC04 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);
EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_RETURNED_CHEQUES' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 08',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC08 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);





EXEC  DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA   => 'CUSTOMER_PROFILE_S', OBJECT_NAME     => 'CUSTS_CARDS_TRANS' ,POLICY_NAME     => 'CRM_DEPOSITS_FILTER 33',FUNCTION_SCHEMA => 'ENBDBA',POLICY_FUNCTION => 'CRM_FILTERS_PACK.FILTER_FUNC33 ',STATEMENT_TYPES => 'SELECT',POLICY_TYPE     => DBMS_RLS.STATIC);





-----ZANJIREH

EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_CHK_OHDEH_OTHER_BANKS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 24',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC24',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_CIF_HAGHIGHI',POLICY_NAME=>'CRM_DEPOSITS_FILTER 25',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC25',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_CIF_HOGHOOGHI',POLICY_NAME=>'CRM_DEPOSITS_FILTER 25',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC25',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'IBAN_SHEBA',POLICY_NAME=>'CRM_DEPOSITS_FILTER 25',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC25',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_CIF_ADDRESS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 26',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC26',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_CIF_DATA',POLICY_NAME=>'CRM_DEPOSITS_FILTER 26',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC26',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_DEP2ACT',POLICY_NAME=>'CRM_DEPOSITS_FILTER 26',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC26',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_DEPOSIT_DOCS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 26',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC26',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_DEPOSIT310',POLICY_NAME=>'CRM_DEPOSITS_FILTER 26',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC26',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_DEPOSIT351',POLICY_NAME=>'CRM_DEPOSITS_FILTER 26',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC26',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_ETEBAR2ACT',POLICY_NAME=>'CRM_DEPOSITS_FILTER 26',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC26',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_LOAN2ACT',POLICY_NAME=>'CRM_DEPOSITS_FILTER 26',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC26',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_DEPOSIT2CIF',POLICY_NAME=>'CRM_DEPOSITS_FILTER 27',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC27',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_CIF2CIF',POLICY_NAME=>'CRM_DEPOSITS_FILTER 28',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC28',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_OUR_CHANK_BANK',POLICY_NAME=>'CRM_DEPOSITS_FILTER 29',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC29',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_OUR_CHQ2OTHERS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 29',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC29',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'OUR_CHQ2OTHERS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 29',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC29',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CHK_OHDEH_BANKS_EN',POLICY_NAME=>'CRM_DEPOSITS_FILTER 30',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC30',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CHK_OHDEH_BANKS_OTHERS',POLICY_NAME=>'CRM_DEPOSITS_FILTER 30',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC30',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_CHK_OHDEH_BANKS_EN',POLICY_NAME=>'CRM_DEPOSITS_FILTER 30',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC30',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_OTHERS_CHQ_INTRA',POLICY_NAME=>'CRM_DEPOSITS_FILTER 31',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC31',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'OTHERS_CHQ_INTRA',POLICY_NAME=>'CRM_DEPOSITS_FILTER 31',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC31',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
EXEC DBMS_RLS.ADD_POLICY(OBJECT_SCHEMA=>'CRM_FA',OBJECT_NAME=>'CRM_FA_OTHER_CHANK_BANK',POLICY_NAME=>'CRM_DEPOSITS_FILTER 32',FUNCTION_SCHEMA=>'ENBDBA',POLICY_FUNCTION=>'CRM_FILTERS_PACK.FILTER_FUNC32',STATEMENT_TYPES=>'SELECT',POLICY_TYPE=>DBMS_RLS.STATIC);
