CREATE TEMPORARY TABLESPACE TEMP02 TEMPFILE '/u02/app/oracle/oradata/orcl/TEMP/temp0202.dbf' size 10M autoextend on maxsize unlimited;
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE TEMP02;

CREATE BIGFILE TEMPORARY TABLESPACE TEMPTBS TEMPFILE '/u02/app/oracle/oradata/orcl/TEMPTBS01.tmp' SIZE 5M AUTOEXTEND ON maxsize unlimited;
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE TEMPTBS;

ALTER TABLESPACE TEMP ADD TEMPFILE '/u01/app/oracle/oradata/dispatch/temp05.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE UNLIMITED;

DROP TABLESPACE temp02 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE UNDOTBS1 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

ALTER TABLESPACE TEMP DROP DATAFILE '/u01/app/oracle/oradata/TEMP201.tmp'


ALTER DATABASE TEMPFILE  '/u01/app/oracle/oradata/TEMP201.tmp' DROP INCLUDING DATAFILES;
	 
ALTER TABLESPACE temp SHRINK SPACE KEEP 256M;