-- -----------------------------------------------------------------------------------
-- FILE NAME    : HTTPS://ORACLE-BASE.COM/DBA/MONITORING/TS_EXTENT_MAP.SQL
-- AUTHOR       : TIM HALL
-- DESCRIPTION  : DISPLAYS GAPS (EMPTY SPACE) IN A TABLESPACE OR SPECIFIC DATAFILE.
-- REQUIREMENTS : ACCESS TO THE DBA VIEWS.
-- CALL SYNTAX  : @TS_EXTENT_MAP (TABLESPACE-NAME) [ALL | FILE_ID]
-- LAST MODIFIED: 25/01/2003
-- -----------------------------------------------------------------------------------
SET SERVEROUTPUT ON SIZE 1000000
SET FEEDBACK OFF
SET TRIMOUT ON
SET VERIFY OFF

DECLARE
  L_TABLESPACE_NAME VARCHAR2(30) := UPPER('&1');
  L_FILE_ID         VARCHAR2(30) := UPPER('&2');

  CURSOR C_EXTENTS IS
    SELECT OWNER,
           SEGMENT_NAME,
           FILE_ID,
           BLOCK_ID AS START_BLOCK,
           BLOCK_ID + BLOCKS - 1 AS END_BLOCK
    FROM   DBA_EXTENTS
    WHERE  TABLESPACE_NAME = L_TABLESPACE_NAME
    AND    FILE_ID = DECODE(L_FILE_ID, 'ALL', FILE_ID, TO_NUMBER(L_FILE_ID))
    ORDER BY FILE_ID, BLOCK_ID;

  L_BLOCK_SIZE     NUMBER  := 0;
  L_LAST_FILE_ID   NUMBER  := 0;
  L_LAST_BLOCK_ID  NUMBER  := 0;
  L_GAPS_ONLY      BOOLEAN := TRUE;
  L_TOTAL_BLOCKS   NUMBER  := 0;
BEGIN
  SELECT BLOCK_SIZE
  INTO   L_BLOCK_SIZE
  FROM   DBA_TABLESPACES
  WHERE  TABLESPACE_NAME = L_TABLESPACE_NAME;

  DBMS_OUTPUT.PUT_LINE('TABLESPACE BLOCK SIZE (BYTES): ' || L_BLOCK_SIZE);
  FOR CUR_REC IN C_EXTENTS LOOP
    IF CUR_REC.FILE_ID != L_LAST_FILE_ID THEN
      L_LAST_FILE_ID  := CUR_REC.FILE_ID;
      L_LAST_BLOCK_ID := CUR_REC.START_BLOCK - 1;
    END IF;
    
    IF CUR_REC.START_BLOCK > L_LAST_BLOCK_ID + 1 THEN
      DBMS_OUTPUT.PUT_LINE('*** GAP *** (' || L_LAST_BLOCK_ID || ' -> ' || CUR_REC.START_BLOCK || ')' ||
        ' FILEID=' || CUR_REC.FILE_ID ||
        ' BLOCKS=' || (CUR_REC.START_BLOCK-L_LAST_BLOCK_ID-1) || 
        ' SIZE(MB)=' || ROUND(((CUR_REC.START_BLOCK-L_LAST_BLOCK_ID-1) * L_BLOCK_SIZE)/1024/1024,2)
      );
      L_TOTAL_BLOCKS := L_TOTAL_BLOCKS + CUR_REC.START_BLOCK - L_LAST_BLOCK_ID-1;
    END IF;
    L_LAST_BLOCK_ID := CUR_REC.END_BLOCK;
    IF NOT L_GAPS_ONLY THEN
      DBMS_OUTPUT.PUT_LINE(RPAD(CUR_REC.OWNER || '.' || CUR_REC.SEGMENT_NAME, 40, ' ') ||
                           ' (' || CUR_REC.START_BLOCK || ' -> ' || CUR_REC.END_BLOCK || ')');
    END IF;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('TOTAL GAP BLOCKS: ' || L_TOTAL_BLOCKS);
  DBMS_OUTPUT.PUT_LINE('TOTAL GAP SPACE (MB): ' || ROUND((L_TOTAL_BLOCKS * L_BLOCK_SIZE)/1024/1024,2));
END;
/

PROMPT
SET FEEDBACK ON