SELECT 'ALTER DATABASE "' + NAME + '" SET RECOVERY SIMPLE;' FROM SYS.SYSDATABASES WHERE NAME NOT IN ('TEMPDB');


SELECT * FROM 
(
SELECT A.NAME, 1 AS COMMAND_ORDER,'USE "'+A.NAME +'";' AS COMMAND FROM SYS.SYSDATABASES A,SYS.SYSALTFILES B
WHERE A.DBID=B.DBID
AND UPPER(B.NAME) LIKE '%LOG%'
UNION ALL
SELECT A.NAME, 2 AS COMMAND_ORDER,'DBCC SHRINKFILE("' + B.NAME + '",1);' AS COMMAND FROM SYS.SYSDATABASES A,SYS.SYSALTFILES B
WHERE A.DBID=B.DBID
AND UPPER(B.NAME) LIKE '%LOG%'
) X ORDER BY 1,2

SELECT 'ALTER DATABASE "' + NAME + '" SET RECOVERY FULL;' FROM SYS.SYSDATABASES WHERE NAME NOT IN ('TEMPDB');
------


use [dbname];
ALTER DATABASE dbname SET RECOVERY SIMPLE;
DBCC SHRINKFILE(filename,1);
ALTER DATABASE dbname SET RECOVERY FULL;
