SELECT * FROM INFORMATION_SCHEMA.TABLES A,INFORMATION_SCHEMA.COLUMNS B
WHERE A.TABLE_NAME=B.TABLE_NAME
AND A.TABLE_SCHEMA=B.TABLE_SCHEMA
AND A.TABLE_TYPE='BASE TABLE'
AND UPPER(B.COLUMN_NAME) LIKE 'USERID'
