--SQL 2016
USE [master]
GO
CREATE LOGIN [DOMAIN\USERNAME] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [DOMAIN\USERNAME]
GO

--SQL 2008
USE [master]
GO
CREATE LOGIN [DOMAIN\USERNAME] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
EXEC master..sp_addsrvrolemember @loginame = N'DOMAIN\USERNAME', @rolename = N'sysadmin'
GO
