ALTER SYSTEM SET AUDIT_SYS_OPERATIONS=TRUE SCOPE=SPFILE;

ALTER SYSTEM SET AUDIT_TRAIL=DB_EXTENDED SCOPE=SPFILE;

STARTUP FORCE;

SHOW PARAMETER AUDIT;


BEGIN
  DBMS_AUDIT_MGMT.INIT_CLEANUP(
    AUDIT_TRAIL_TYPE => DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD,
    DEFAULT_CLEANUP_INTERVAL => 240 /*HOURS*/
  );
END;

CREATE TABLESPACE AUDIT_DATA DATAFILE '/u01/app/oracle/oradata/enbdb/datafiles/audit_data01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;


BEGIN
  DBMS_AUDIT_MGMT.SET_AUDIT_TRAIL_LOCATION(
    AUDIT_TRAIL_TYPE => DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD,
    AUDIT_TRAIL_LOCATION_VALUE => 'AUDIT_DATA'
  );
END;


SELECT PARAMETER_NAME, PARAMETER_VALUE, AUDIT_TRAIL FROM DBA_AUDIT_MGMT_CONFIG_PARAMS WHERE AUDIT_TRAIL = 'STANDARD AUDIT TRAIL';

SELECT OWNER,SEGMENT_NAME,TABLESPACE_NAME FROM DBA_SEGMENTS WHERE SEGMENT_NAME ='AUD$';

$ORACLE_HOME/rdbms/admin/secconf.sql


SELECT  * FROM DBA_STMT_AUDIT_OPTS;

SELECT * FROM DBA_PRIV_AUDIT_OPTS;
SELECT * FROM DBA_OBJ_AUDIT_OPTS;
SELECT * FROM ALL_DEF_AUDIT_OPTS;
  
SELECT TO_CHAR(X.LAST_ARCHIVE_TS,'YYYYMMDD HH24MISS','NLS_CALENDAR=PERSIAN') FROM DBA_AUDIT_MGMT_LAST_ARCH_TS X  

CREATE TABLE SYS.AUD_13930726 AS SELECT * FROM SYS.AUD$ X WHERE X.NTIMESTAMP# BETWEEN TO_DATE('13930726','YYYYMMDD','NLS_CALENDAR=PERSIAN') AND TO_DATE('13930727','YYYYMMDD','NLS_CALENDAR=PERSIAN');



BEGIN
  DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(AUDIT_TRAIL_TYPE  => DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD,
                                             LAST_ARCHIVE_TIME => TO_DATE('20141001 190000',
                                                                          'YYYYMMDD HH24MISS'));
END;


  
BEGIN
  DBMS_AUDIT_MGMT.CLEAN_AUDIT_TRAIL(AUDIT_TRAIL_TYPE        => DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD,
                                    USE_LAST_ARCH_TIMESTAMP => TRUE);
END;

  
--------------
BEGIN
  DBMS_SCHEDULER.CREATE_JOB (
    JOB_NAME   => 'DAILY_AUDIT_ARCHIVE_TIMESTAMP',
    JOB_TYPE   => 'PLSQL_BLOCK',
    JOB_ACTION => 'BEGIN DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(AUDIT_TRAIL_TYPE =>
                   DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD,LAST_ARCHIVE_TIME => SYSDATE-10); END;',
    START_DATE => SYSDATE,
    REPEAT_INTERVAL => 'FREQ=HOURLY;INTERVAL=24',
    ENABLED    =>  TRUE,
    COMMENTS   => 'CREATE AN ARCHIVE TIMESTAMP'
  );
END;


BEGIN
  DBMS_AUDIT_MGMT.CREATE_PURGE_JOB(
    AUDIT_TRAIL_TYPE           => DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD,
    AUDIT_TRAIL_PURGE_INTERVAL => 24 /* HOURS */,
    AUDIT_TRAIL_PURGE_NAME     => 'DAILY_AUDIT_PURGE_JOB',
    USE_LAST_ARCH_TIMESTAMP    => TRUE
  );
END;

SELECT JOB_NAME, NEXT_RUN_DATE, STATE, ENABLED FROM DBA_SCHEDULER_JOBS WHERE JOB_NAME LIKE '%AUDIT%'; 

SELECT JOB_NAME,JOB_STATUS,AUDIT_TRAIL,JOB_FREQUENCY FROM DBA_AUDIT_MGMT_CLEANUP_JOBS;