BEGIN
  DBMS_AUDIT_MGMT.INIT_CLEANUP(AUDIT_TRAIL_TYPE => DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD,DEFAULT_CLEANUP_INTERVAL => 240 /*hours*/);
END;

DECLARE
  DATE1       DATE;
  DATE_START  DATE := TO_DATE('13961124 000000','YYYYMMDD HH24MISS','NLS_CALENDAR=PERSIAN');
  DATE_FINISH DATE := TO_DATE('13961126 000000','YYYYMMDD HH24MISS','NLS_CALENDAR=PERSIAN');
BEGIN
  DATE1 := DATE_START;
  WHILE DATE1<DATE_FINISH LOOP
    BEGIN
      DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(AUDIT_TRAIL_TYPE => DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD,LAST_ARCHIVE_TIME => DATE1);
    END;
    BEGIN
      DBMS_AUDIT_MGMT.CLEAN_AUDIT_TRAIL(AUDIT_TRAIL_TYPE => DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD,USE_LAST_ARCH_TIMESTAMP => TRUE);
    END;
    DATE1 := DATE1 + 1 / 1440; --ONE MINUTE
  END LOOP;

END;
