SELECT
TABLE_SCHEMA 'DATABASE',
A.TABLE_NAME ,
SUM(DATA_LENGTH + INDEX_LENGTH) AS 'DBSIZE',
SUM(TABLE_ROWS) AS DBROWS,
SUM(AUTO_INCREMENT) AS DBAUTOINCCOUNT
FROM INFORMATION_SCHEMA.TABLES A
WHERE A.TABLE_SCHEMA='tamashakhoneh_db'
GROUP BY TABLE_SCHEMA,A.TABLE_NAME
ORDER BY 3 DESC
;